---
title: "Model"
author: "Alessio Drigatti"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#required packages
list.of.packages <- c("foreign","bnlearn","stats","pROC", "performance", "see", "DHARMa", "dplyr")

#install if necessary
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

#load all packages
lapply(list.of.packages, library, character.only = TRUE)
```



```{r}
data.full <- readRDS("data/stroke_original.rds")
data.interp <- readRDS("data/stroke_interpolate.rds")
```


```{r}
data.interp
```

```{r}
hist(data$age, breaks=150)
```




```{r}
variables <- c("gender", "age", "hypertension", "heart_disease", "avg_glucose_level", "bmi", "smoking_status", "stroke")

data.interp.fac <- data.interp %>%
  select(variables) %>%
  mutate(avg_glucose_level = case_when(
    avg_glucose_level <= 100 ~ 0,
    avg_glucose_level > 100 & avg_glucose_level <= 126 ~ 1,
    avg_glucose_level > 126 ~ 2,
    TRUE ~ avg_glucose_level
  )) %>%
  mutate(age = case_when(
    age <= 30 ~ 0,
    age > 30 & age < 60 ~ 1,
    age >= 60 ~ 2,
    TRUE ~ age
  )) %>%
  mutate(bmi = ifelse(bmi > 30, 1, 0)) %>%
  mutate(across(everything(), as.factor))

```


```{r}
set.seed(42)
data <- data.interp.fac

predictors <- colnames(data)[!colnames(data) %in% c("stroke")]
trainIndex <- createDataPartition(data$stroke, p = 0.8, list = FALSE, times = 1)
data.model <- data[trainIndex, ]
data.val <- data[-trainIndex, ]
```



```{r}
bn_structure.full <- tabu(data.model)
graphviz.plot(bn_structure.full)
```


```{r}
blacklist <- rbind(
  cbind(variables, "age"),
  cbind(variables, "gender"),
  cbind("age", "gender"),
  cbind("gender", "age")
)

whitelist <- rbind(
  cbind("hypertension", "stroke"),
  cbind("smoking_status", "stroke"),
  cbind("avg_glucose_level", "stroke"),
  cbind("bmi", "stroke"),
  cbind("age", "stroke")
)


bn_structure.bl <- tabu(data.model, blacklist = blacklist)
bn_structure.bl.wl <- tabu(data.model, blacklist = blacklist, whitelist = whitelist)
graphviz.plot(bn_structure.bl)
graphviz.plot(bn_structure.bl.wl)
```
```{r}
get_ancestors <- function(bn_fitted, node, depth) {
  if (depth == 0) return(node)
  parent_nodes <- parents(bn_fitted, node)
  if (length(parent_nodes) == 0) return(node)
  unique(c(node, unlist(lapply(parent_nodes, function(p) get_ancestors(bn_fitted, p, depth - 1)))))
}

# Updated prediction function
predict_bn_stroke <- function(bn_fitted, data.val, depth = 10) {
  # Get the ancestor nodes of "stroke" up to a certain depth
  ancestor_nodes <- get_ancestors(bn_fitted, "stroke", depth)
  ancestor_nodes <- setdiff(ancestor_nodes, "stroke") # Remove the target node itself
  
  # Function to gather evidence for a single observation
  get_evidence <- function(row, ancestor_nodes) {
    # Extract values for ancestor nodes from the row
    evidence <- setNames(as.list(row[ancestor_nodes]), ancestor_nodes)
    return(evidence)
  }
  
  # Calculate conditional probabilities for "stroke" being "1"
  prob_predictions <- sapply(1:nrow(data.val), function(i) {
    evidence <- get_evidence(data.val[i, ], ancestor_nodes)
    cpquery(bn_fitted, event = (stroke == "1"), evidence = evidence, method = "lw")
  })
  return(prob_predictions)
}
```



```{r}
bn_fitted <- bn.fit(bn_structure.bl, data = data.model)
prob_predictions <- predict_bn_stroke(bn_fitted, data.val)

roc_obj <- roc(response = data.val$stroke, predictor = prob_predictions)

#Blacklist only
plot(roc_obj, main = "")
auc_obj <- auc(roc_obj)

# Add AUC to the plot
text(x = 0.2, y = 0.1, labels = paste("AUC =", round(auc_obj, 3)), cex = 1.2)
```

```{r}
bn_fitted <- bn.fit(bn_structure.bl.wl, data = data.model)
prob_predictions <- predict_bn_stroke(bn_fitted, data.val)

roc_obj <- roc(response = data.val$stroke, predictor = prob_predictions)

#Black & Whitlist
plot(roc_obj, main = "")
auc_obj <- auc(roc_obj)

# Add AUC to the plot
text(x = 0.2, y = 0.1, labels = paste("AUC =", round(auc_obj, 3)), cex = 1.2)
```



```{r}
model.logistic <- glm(stroke ~ ., data = data.interp.fac, family = binomial)
summary(model.logistic)
```



```{r}
predicted_probs <- predict(model.logistic, newdata = data.val, type = "response")

roc_obj <- roc(response = data.val$stroke, predictor = predicted_probs)

auc_obj <- auc(roc_obj)
# Logistic Model
plot(roc_obj, main = "")

text(x = 0.2, y = 0.1, labels = paste("AUC =", round(auc_obj, 3)), cex = 1.2)
```



















